CREATE TABLE LOGIN_MST (EMAIL varchar,PASSWORD varchar,USER varchar,MOBILE varchar,PRIMARY KEY (email));
INSERT INTO LOGIN_MST (EMAIL,PASSWORD,USER,MOBILE) VALUES('admin@gmail.com','123','s','8569741236');
INSERT INTO LOGIN_MST (EMAIL,PASSWORD,USER) VALUES('user@gmail.com','123','c','7945126589');